### ISSUE TITLE
fails to install in python 3.10

### ISSUE THREAD

**Issue by edkerk** [biosustain/swiglpk#51]
**edit:** the below was with python 3.10.0. It works fine with 3.9.7.

Not sure this is something you can address, but [GitHub Actions](https://github.com/SysBioChalmers/yeast-GEM/runs/3967864108?check_suite_focus=true#step:4:250) fails to install `swiglpk 5.0.3`:

```python
pip install -r requirements/ci-requirements.txt
[...]
ERROR: Could not find a version that satisfies the requirement swiglpk==5.0.3 (from versions: 0.1.0, 1.0.0, 1.2.12, 1.2.13, 1.2.14, 1.4.4, 1.5.0b0, 1.5.0, 1.5.1, 4.64.0b0, 4.65.0, 4.65.1, 5.0.0)
ERROR: No matching distribution found for swiglpk==5.0.3
```
where `ci-requirements.txt` contains:
```python
swiglpk==5.0.3
    # via
    #   cobra
    #   optlang
```

Meanwhile, forcing version 5.0.0 in `ci-requirements.txt` [results](https://github.com/edkerk/yeast-GEM/runs/4450708188?check_suite_focus=true#step:4:251) in:

```python
Collecting swiglpk==5.0.0
  Downloading swiglpk-5.0.0.tar.gz (32 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /opt/hostedtoolcache/Python/3.10.0/x64/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-wkn7cwwj
       cwd: /tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/
  Complete output (12 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py", line 52, in <module>
      glpk_header_dirname = find_glpk_header()
    File "/tmp/pip-install-39pg8iv7/swiglpk_e7c0d6367e9b4cc9b9ebc51e1af871d9/setup.py", line 35, in find_glpk_header
      glpsol_dirname = os.path.dirname(subprocess.check_output(['which', 'glpsol']))
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/subprocess.py", line 524, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['which', 'glpsol']' returned non-zero exit status 1.
  Trying to determine glpk.h location
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/9b/49/260f20672b1f11138e240df219deb496ab9d17a5b8f623334b7e49e1e089/swiglpk-5.0.0.tar.gz#sha256=7b1e30bc401ab1ed638253ac93da5757d47247bce390b0e614b6cddb8838d1f7 (from https://pypi.org/simple/swiglpk/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement swiglpk==5.0.0 (from versions: 0.1.0, 1.0.0, 1.2.12, 1.2.13, 1.2.14, 1.4.4, 1.5.0b0, 1.5.0, 1.5.1, 4.64.0b0, 4.65.0, 4.65.1, 5.0.0)
ERROR: No matching distribution found for swiglpk==5.0.0
```

**Comment by Viech** [comment]
After hitting this problem quite a few times in different contexts, I want to note that this issue and closely related ones will be re-experienced by your users with every release of a new Python major version.

Here is what happens every time, as far as I understand it:

1. Users install swiglpk, thinking this gives them everything they need. Since normally there is a wheel and that wheel appears to include GLPK (as e.g. the `Python:3.9` docker image lets you solve problems after installing only `swiglpk` from pip), they are for that moment correct.
2. A new Python major version is released. There are no wheels for this version yet and there won't be any for a couple more days to months. pip sees that there are no wheels and downloads the source instead. It executes `setup.py`.
4. Now either (a) `setup.py` does not find GLPK installed to link swiglpk against (this issue) or (b) GLPK is installed but `setup.py` fails to locate it as the location code is not platform-independent (#40) or (c) the user has GLPK but not SWIG  or some other build-time dependency installed (#36).

I don't know a good long-term solution but I suggest to at least make the error messages produced by `setup.py` really explain the situation, like I tried above. This would give users running swiglpk as part of a CI/CD pipeline a heads-up warning that it will break again when they bump the Python version another time, and it would allow them to work around the issue by making sure every dependency necessary for a source build is installed (and by patching `setup.py` to find it, if necessary).

**Comment by cdiener** [comment]
I sent in a PR to support 3.10. 

@Viech this is more an issue of a lack of contributors more than anything else. We have very few contributors across the COBRA ecosystem at the moment and new Python versions will always require at least a minimal amount of adjustments. We definitely welcome PRs to fix those issues though :)

An additional work around is to use cones with a supported Python version. swiglpk and optlang are on conda-forge and have a few more contributors.

**Comment by cdiener** [comment]
Okay, this time it's really fixed. Wheels for 3.10 are now provided for swiglpk 5.0.4.

**Comment by Midnighter** [comment]
Great, thank you @cdiener !
